# Setup
# Add users netlify identity
# https://app.netlify.com/sites/[SITENAME]/settings/identity#external-providers
# enable git gateway
# https://app.netlify.com/sites/[SITENAME]/settings/identity#git-gateway

# Doc
# https://preview-auth-doc--netlify-cms-www.netlify.app/docs/customization/
#
backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
  #  branch: main

local_backend: true

#SETTINGS
site_url: https://localhost:8080
logo_url: https://localhost:8080/img/favicon-196x196
display_url: https://URL
media_folder: "src/images"
public_folder: "/images"
show_preview_links: true
search: true
# publish_mode: editorial_workflow

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  # -----------------------------------------------------------------
  # Collection Authors
  # -----------------------------------------------------------------
  - name: authors
    label: Authors
    folder: "src/content/authors"
    slug: "{{title}}"
    create: true
    required: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { name: name, label: Name, required: false }
      - { name: twitter, label: "Twitter @", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }

  # -----------------------------------------------------------------
  # Collection Pages
  # -----------------------------------------------------------------
  - name: Page
    label: Page
    folder: "src/content/page"
    slug: "{{title}}"
    create: true
    required: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { name: slugcustom, label: "slug", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }
      # Author
      - name: author
        label: Author
        widget: relation
        collection: authors
        searchFields: [name, title]
        valueField: "{{slug}}"
        display_fields: ["title"]
        required: false
        multiple: true

  # -----------------------------------------------------------------
  # Post Collection
  # -----------------------------------------------------------------
  - label: "posts"
    label_singular: "post"
    name: "posts"
    description: "All Posts"
    folder: "src/content/post"
    slug: "{{year}}-{{month}}-{{day}}_{{title}}"
    preview_path: session/{{slug}}
    create: true
    delete: true
    editor:
      preview: true
    # Overview

    # summary: "{{ title }} | {{date | date('DD MMM hh:mm yy')}} | order: {{order}} // Draft: {{eleventyExcludeFromCollections}}"
    sortable_fields: ['eleventyExcludeFromCollections', 'title', 'date']
    # SESSION FILTERS
    view_filters:
      - label: Drafts
        field: eleventyExcludeFromCollections
        pattern: true
    # SESSION GROUPS
    view_groups:
      - label: "Date: "
        field: date
        pattern: "([0-9]+(-[0-9]+)+)"
      - label: Drafts
        field: eleventyExcludeFromCollections
      - label: collections
        field: tags

    # FIELDS
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }

      # Gallery
      - label: "Gallery"
        name: "gallery"
        widget: "list"
        fields:
          - label: image
            name: image
            widget: object
            fields:
              - {label: image, name: image, widget: image }
              - {label: title, name: title, widget: string, required: false}
              - {label: Description, name: figcaption, widget: text, required: false}

      # Author
      - name: author
        label: Author
        widget: relation
        collection: authors
        searchFields: [name, title]
        valueField: "{{slug}}"
        display_fields: ["title"]
        required: false

      # Date
      - label: "Date published"
        name: "date"
        widget: "datetime"
        date_format: "DD.MM.YYYY"
        time_format: "HH:mm"
        format: "YYYY-MM-DD HH:mm:ss"
        picker_utc: false

      # Tags
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        required: false
        options: ["css", "html", "11ty", "a11y"]

        # 11ty settings
      - { label: "Order", name: "order", widget: "number", required: false, default="100" }
      - { label: "Draft Mode", name: "eleventyExcludeFromCollections", widget: "boolean", default: true, required: false}

      # Template selector
      - label: "Layout template"
        name: "layout"
        widget: "select"
        multiple: false
        required: true
        default: page.njk
        options: ["page-post.njk", "page.njk"]

      # Navigation
      # - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
      #   name: "eleventyNavigation"
      #   required: false
      #   widget: "object"
      #   collapsed: true
      #   fields:
      #     - { label: "Key", name: "key", widget: "string", required: false }
      #     - { label: "Order", name: "order", widget: "number", default: 0, required: false }

      # Files
      - label: "Files"
        name: "files"
        widget: "file"
        required: false
        choose_url: true
        allow_multiple: true
        media_folder: "/src/files"


  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about"
        file: "src/content/about.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Team
            name: team
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Photo, name: photo, widget: image}
      - label: "Locations Page"
        name: "locations"
        file: "src/content/locations.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Locations
            name: locations
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Address, name: address, widget: string}
