# Setup for
# Add users aka identity
# https://app.netlify.com/sites/[SITENAME]/settings/identity#external-providers
# enable git gateway
# https://app.netlify.com/sites/[SITENAME]/settings/identity#git-gateway

# Doc
# https://preview-auth-doc--netlify-cms-www.netlify.app/docs/customization/
#
backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
  # main
  ### enable below lines for github integration ###
  # name: github
  use_large_media_transforms_in_media_library: false

# IMAGES
media_folder: "src/images"
public_folder: "/images"

#SETTINGS
logo_url: https://URL/assets/img/bars.svg
site_url: https://URL
display_url: https://URL
show_preview_links: true
search: true
# publish_mode: editorial_workflow

# Local
# Please run "npx netlify-cms-proxy-server" for local backend
# local_backend: true
# when using a custom proxy server port
# url: http://localhost:8085/api/v1
# when accessing the local site from a host other than 'localhost' or '127.0.0.1'
# allowed_hosts: ['192.168.0.1']

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: authors
    label: Authors
    folder: "src/content/authors"
    create: true
    required: false
    fields:
      - {name: name, label: Name}
      - {name: twitterHandle, label: "Twitter Handle"}
      - {name: bio, label: Bio, widget: text}

  # Post
  - label: "posts"
    label_singular: "post"
    name: "posts"
    description: "All Posts"
    folder: "src/content/post"
    slug: "{{year}}-{{month}}-{{day}}_{{title}}"
    preview_path: session/{{slug}}
    create: true
    delete: true
    editor:
      preview: true
    # Overview

    # summary: "{{ title }} | {{date | date('DD MMM hh:mm yy')}} | order: {{order}} // Draft: {{eleventyExcludeFromCollections}}"
    sortable_fields: ['eleventyExcludeFromCollections', 'title', 'date']
    # SESSION FILTERS
    view_filters:
      - label: Drafts
        field: eleventyExcludeFromCollections
        pattern: true
    # SESSION GROUPS
    view_groups:
      - label: "Date: "
        field: date
        pattern: "([0-9]+(-[0-9]+)+)"
      - label: Drafts
        field: eleventyExcludeFromCollections
      - label: collections
        field: tags

    # FIELDS
    fields:
      - { label: "Title", name: "title", widget: "string" }
      # TIME
      - label: "Date published"
        name: "date"
        widget: "datetime"
        date_format: "DD.MM.YYYY"
        time_format: "HH:mm"
        format: "YYYY-MM-DD HH:mm:ss"
        picker_utc: false

      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }


      # textimotional
      - label: "Gallery"
        name: "gallery"
        widget: "list"
        fields:
          - label: image
            name: image
            widget: object
            fields:
              - {label: image, name: image, widget: image }
              - {label: title, name: title, widget: string, required: false}
              - {label: Description, name: figcaption, widget: text, required: false}


      # Relation
      - name: author
        label: Author
        widget: relation
        collection: authors
        searchFields: [name, twitterHandle]
        valueField: name

      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        required: false
        options: ["css", "html", "11ty", "a11y"]

        # 11ty settings
      - { label: "Order", name: "order", widget: "number", required: false, default="100" }
      - { label: "Draft Mode", name: "eleventyExcludeFromCollections", widget: "boolean", default: true, required: false}

      # Template selector
      - label: "Layout template"
        name: "layout"
        widget: "select"
        multiple: false
        required: true
        default: page.njk
        options: ["page-post.njk", "page.njk"]

      # Navigation
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        required: false
        widget: "object"
        collapsed: true
        fields:
          - { label: "Key", name: "key", widget: "string", required: false }
          - { label: "Order", name: "order", widget: "number", default: 0, required: false }

      # Files
      - { label: 'File', name: 'file', widget: 'file', required: false }

      # - label: "Files"
      #   name: "files"
      #   widget: "file"
      #   required: false
      #   choose_url: true
        # media_folder: "/src/files"
