backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
  # main
  ### enable below lines for github integration ###
  # name: github
  use_large_media_transforms_in_media_library: false

# IMAGES
media_folder: "src/images"
public_folder: "/images"

#SETTINGS
logo_url: https://URL/assets/img/bars.svg
site_url: https://URL
display_url: https://URL
show_preview_links: true
search: true
# publish_mode: editorial_workflow

# Local
# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# when using a custom proxy server port
url: http://localhost:8085/api/v1
# when accessing the local site from a host other than 'localhost' or '127.0.0.1'
allowed_hosts: ['192.168.0.1']
# allowed_hosts: ['https://webinardays.com/']


slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  # SESSIONS
  - label: "Session"
    name: "session"
    folder: "src/content/session"
    preview_path: session/{{slug}}
    create: true
    delete: true
    slug: "{{title}}-{{speaker}}-{{day}}-{{month}}" # filename
    editor:
      preview: true
    # Overview
    description: "WebinarDays 2021 Sessions"
    summary: "{{speaker}} {{title }} | {{date | date('DD MMM hh:mm yy')}} | order: {{order}} // Draft: {{eleventyExcludeFromCollections}}"
    sortable_fields: ['speaker', 'title', 'date']
    # SESSION FILTERS
    view_filters:
      - label: "Day 1"
        field: tags
        pattern: 'dayone'
      - label: "Day 2"
        field: tags
        pattern: 'daytwo'
      - label: "Day 3"
        field: tags
        pattern: 'daythree'
      - label: "featured"
        field: tags
        pattern: 'featuredsession'
      - label: Drafts
        field: eleventyExcludeFromCollections
        pattern: true
    # SESSION GROUPS
    view_groups:
      - label: "Date: "
        field: date
        pattern: "([0-9]+(-[0-9]+)+)"
      - label: Drafts
        field: eleventyExcludeFromCollections
      - label: collections
        field: tags

    # FIELDS
    fields:
      - { label: "Session Title", name: "title", widget: "string" }
      - { label: "speaker name", name: "speaker", widget: "string" }
      - { label: "session type", name: "sessiontype", widget: "string", required: false }
      - { label: "speaker info", name: "speakerinfo", widget: "string", required: false }
      - { label: "speaker company", name: "speakercompany", widget: "string", required: false }
      - { label: "speaker Title", name: "speakertitle", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }
      # TIME
      - label: "Start time"
        hint: "Session Start time"
        name: "date"
        widget: "datetime"
        date_format: "DD.MM.YYYY"
        time_format: "HH:mm"
        format: "YYYY-MM-DD HH:mm:ss"
        picker_utc: false
      - label: "Start time"
        name: "end"
        widget: "datetime"
        date_format: "DD.MM.YYYY"
        time_format: "HH:mm"
        format: "YYYY-MM-DD HH:mm:ss"
        picker_utc: false

      - { label: "Body", name: "body", widget: "markdown", required: false }

      - label: "Collection"
        name: "tags"
        widget: "select"
        multiple: true
        min: 0
        max: 2
        options: ["featuredsession", "dayone", "daytwo", "daythree","none"]
        default: ["none"]
      - { label: "Order", name: "order", widget: "number", required: false, default="100" }
      - { label: "Draft", name: "eleventyExcludeFromCollections", widget: "boolean", default: true, hint: "Is the session Hidden on the site"}

# ------------------------------------------
# INFO
# ------------------------------------------
  - label: "info"
    name: "info"
    description: "Info paragrahps"
    folder: "src/content/info"
    preview_path: info/{{slug}}
    create: true
    delete: false
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "subject", name: "subject", widget: "string" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "order", name: "order", widget: "string" }
      - { label: "Draft", name: "eleventyExcludeFromCollections", widget: "boolean", default: true}
      - { label: "Body", name: "body", widget: "markdown" }

