# Setup for
# Add users aka identity
# https://app.netlify.com/sites/[SITENAME]/settings/identity#external-providers
# enable git gateway
# https://app.netlify.com/sites/[SITENAME]/settings/identity#git-gateway

#
backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
  # main
  ### enable below lines for github integration ###
  # name: github
  use_large_media_transforms_in_media_library: false

# IMAGES
media_folder: "src/images"
public_folder: "/images"

#SETTINGS
logo_url: https://URL/assets/img/bars.svg
site_url: https://URL
display_url: https://URL
show_preview_links: true
search: true
# publish_mode: editorial_workflow

# Local
# Please run "npx netlify-cms-proxy-server" for local backend
# local_backend: true
# when using a custom proxy server port
# url: http://localhost:8085/api/v1
# when accessing the local site from a host other than 'localhost' or '127.0.0.1'
# allowed_hosts: ['192.168.0.1']

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  # SESSIONS
  - label: "post"
    name: "post"
    folder: "src/content/post"
    preview_path: session/{{slug}}
    create: true
    delete: true
    # slug: "{{title}}-{{speaker}}-{{day}}-{{month}}" # filename
    editor:
      preview: true
    # Overview
    description: "Post"
    summary: "{{title }} | {{date | date('DD MMM hh:mm yy')}} | order: {{order}} // Draft: {{eleventyExcludeFromCollections}}"
    sortable_fields: ['eleventyExcludeFromCollections', 'title', 'date']
    # SESSION FILTERS
    view_filters:
      - label: "Day 1"
        field: tags
        pattern: 'dayone'
      - label: "Day 2"
        field: tags
        pattern: 'daytwo'
      - label: "Day 3"
        field: tags
        pattern: 'daythree'
      - label: "featured"
        field: tags
        pattern: 'featuredsession'
      - label: Drafts
        field: eleventyExcludeFromCollections
        pattern: true
    # SESSION GROUPS
    view_groups:
      - label: "Date: "
        field: date
        pattern: "([0-9]+(-[0-9]+)+)"
      - label: Drafts
        field: eleventyExcludeFromCollections
      - label: collections
        field: tags

    # FIELDS
    fields:
      - { label: "Title", name: "title", widget: "string" }

      # TIME
      - label: "date published"
        hint: "date yo"
        name: "date"
        widget: "datetime"
        date_format: "DD.MM.YYYY"
        time_format: "HH:mm"
        format: "YYYY-MM-DD HH:mm:ss"
        picker_utc: false

        - { label: "Image", name: "image", widget: "image", required: false }
        - { label: "Body", name: "body", widget: "markdown", required: false }

      - label: "Collections"
        name: "tags"
        widget: "select"
        multiple: true
        min: 0
        max: 2
        required: false
        options: ["css", "html", "11ty", "a11y"]

      - { label: "Order", name: "order", widget: "number", required: false, default="100" }
      - { label: "Draft", name: "eleventyExcludeFromCollections", widget: "boolean", default: true, hint: "Is the session Hidden on the site"}

      - label: "layout"
        name: "layout"
        widget: "select"
        multiple: false
        required: true
        options:
          - { label: "Post template", value: "page-post.njk" }
          - { label: "page template", value: "page.njk" }
        default: ["page-post"]

